### ISSUE TITLE
Ajouter du code

### ISSUE THREAD

**Issue by BartholomewPanda** [teamMadScientist/celerity#1]
Ajouter du code.

**Comment by ZetaKebab** [comment]
Plébéien !

**Comment by wolfnux** [comment]
Il n'y a effectivement pas beaucoup de code.
Je pense que ce ticket devrait être ouvert à nouveau.
Cordialement,

**Comment by BartholomewPanda** [comment]
+1

**Comment by wolfnux** [comment]
__Question__
A quand la prochaine update ?
